spring:
  kafka:
    bootstrap-servers: localhost:9092


    #Producer Configuration
    producer:
      bootstrap-servers: localhost:9092
      #As key is string we are using StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # As value will be an Json Object we will be using Json Serialiser
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  
    #Consumer Configuration
    consumer:
      bootstrap-servers: localhost:9092
      group-id: alpha
      auto-offset-reset: earliest
      # As while consuming, the key will be string using StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # As we are consuming the same json object it will be Json Deserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      


      
        